a: *.cpp
	g++  table.cpp iterator.cpp breadthFirstIterator.cpp depthFirstIterator.cpp floor.cpp test.cpp -o task1
	
run:
	./task1
	
clean:
	rm *.o task1

tar: 
	tar -cvz *.cpp makefile *.h -f finalProject.tar