name: cpplint
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --linelength=100 --filter=-whitespace,-whitespace/braces,-legal/copyright,-build/include_what_you_use,-build/header_guard,-build/namespaces,-runtime/explicit,-build/include_order,-build/include_subdir,-runtime/threadsafe_fn,-readability/todo,-runtime/references,-readability/multiline_comment,-readability/braces,-runtime/int,-readability/namespace --quiet --extensions=h,cpp,hpp $( find . -name \*.h -or -name \*.cc | grep -vE "^\.\/build\/" )
